### ISSUE TITLE
Question about pulling previous versions

### ISSUE THREAD

**Issue by dani3876** [OuhscBbmc/BbmcResources#11]
@wibeasley One of the changes I added prior to your fixes got lost in the mix. The portfolio as it is currently on the website is not mobile friendly. I had changed it to address that, but those changes reverted somewhere in one of the merges--any ideas how to get it back? When I pull up the history, it only shows the specific changes I made to certain sections, and I can't find that one. I hope it isn't totally lost.

**Comment by dani3876** [comment]
Nevermind, I think I got it sorted out. Sorry!

**Comment by wibeasley** [comment]
@dani3876, cool.  And unless something really went wrong, nothing should be lost forever on Git, because you can always go back through the [commits](https://github.com/OuhscBbmc/BbmcResources/commits/master).
