### ISSUE TITLE
List of reproducible studies

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/BbmcResources#2]
@dani3876 (cc: @DavidBard), there have been several times when it would have been nice to refer someone to a list of research publications we've been involved with that are reproducible.  Is there a place in the upcoming website that can naturally accommodate this list?

* https://github.com/OuhscBbmc/DeSheaToothakerIntroStats
* https://github.com/OuhscBbmc/Wats
* https://github.com/LiveOak/UcaBullying
* https://github.com/LiveOak/LylesCarbonSteelCorrosion

**Comment by dani3876** [comment]
We can certainly add a section!

**Comment by wibeasley** [comment]
Great, @dani3876.  Would it be a separate html file in your bootstrap website?  I don't have a strong preference.  Just do what you think will be easiest to maintain in the future.  Hopefully we add 5+ reproducible projects to this list every year.

If it affects your decision, eventually I'd like to add a similar page/section called something like "Interactive  & Static Reports" that lists stuff like the C1 nursing dashboard and the TFCBT checklist.

Will you please add a section/page the following description and table?  My preference is that the list is actually a table with three columns: (a) the hyperlinked name,  (b) a ~2 sentence description of each project, (c) release year.  I'm considering adding other columns (eg a list of specific publications produced by each repository), but this is a good start.  There are two projects of mine from outside the BBMC.  I want to include them for now to represent the range of studies the BBMC is capable of.  I'll remove them once the list if better filled  out.

> [Reproducible research](http://reproducibleresearch.net/) is a mentality and technique that makes an investigation transparent for outsiders to inspect and potentially conduct on their own.  Here are some code & report repositories of studies conducted by BBMC members.  Many more are in the pipeline, to be released in 2015 & 2016.

| Project | Description | First Published Product | 
| --------- | --------------- | --------------------- |
| [MReporting](https://github.com/OuhscBbmc/MReportingPublic) | Aggregate and de-identified datasets to communicate the products of Oklahoma's MIECHV evaluation | 2015 |
| [*Introductory Statistics for the Health Sciences*](https://github.com/OuhscBbmc/DeSheaToothakerIntroStats) | Graphs for the book by Lise DeShea and Larry E. Toothaker | 2015 |
| [UCA Bullying](https://github.com/LiveOak/UcaBullying) | Analysis of Middle School Behavior for Paul Nail and the University of Central Arkansas | 2015 |
| [WATS Plot](https://github.com/OuhscBbmc/Wats) | Wrap Around Time Series | 2014 |
| [Lyles Carbon Steel Corrosion](https://github.com/LiveOak/LylesCarbonSteelCorrosion) | Anaerobic hydrocarbon and fatty acid metabolism by syntrophic bacteria and their impact on carbon steel corrosion | 2014 |

**Comment by dani3876** [comment]
Well, I had started this sort of portfolio-type section for research projects. I can change the title from "projects" to "research" and have the reproducible research piece right above this? 
![a](https://cloud.githubusercontent.com/assets/10676177/8879989/e5fc05e6-31fa-11e5-9f6a-6152335d7609.png)

**Comment by wibeasley** [comment]
That sounds like a good place.  I'm not even sure you need to change the title.  Both seem fine to me.
