### ISSUE TITLE
Dynamic `USE` sql statement

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/BbmcResources#20]
@mand9472, please figure out a way to do the `USE` statement w/ variables.

Instead of 
```r
USE [go_round_in_circles]
```

Something like this (although this doesn't work):

```sql
DECLARE @database_name nvarchar(255); SET @database_name = '[go_round_in_circles]'
DECLARE @use nvarchar(max); SET @use = 'USE ' + @database_name
print 'database use  : ' + @use
EXECUTE sp_executesql @use
```

Here are two possible helpers:
* http://stackoverflow.com/questions/38852720/variable-for-use-database
* https://www.sqlservercentral.com/Forums/Topic750586-338-1.aspx

**Comment by mand9472** [comment]
The below sql should work 

DECLARE @database_name nvarchar(255); SET @database_name = '[go_round_in_circles]'
DECLARE @use nvarchar(max); SET @use = 'USE ' + @database_name
print 'database use  : ' + @use
EXEC ( @use + ';' + 'any other statements to execute')

I have also emailed the sql for the above more descriptively ,Im closing this issue please let me know if you need this to be reopened.
