### ISSUE TITLE
update R and hit error for OuhscMunge

### ISSUE THREAD

**Issue by yutiantang** [OuhscBbmc/BbmcResources#32]
@wibeasley I am updating my R to the latest 4.0.2 and hit this error for installing "OuhscMunge":
`Error in stop(github_error(req)) : 
  API rate limit exceeded for 157.142.42.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (403)`

Is it because I install from home instead of at office? Thanks!

**Comment by wibeasley** [comment]
I don't think it's related to the package itself.  What did you get when you searched for this error? See https://github.com/r-lib/remotes/issues/210.

Here's another resource that I like from Jenny Bryan and Jim Hester: https://happygitwithr.com/github-pat.html

**Comment by wibeasley** [comment]
@yutiantang, I assume this has been resolved.  If you remember, I'm curious to know how it was.
